language: php
dist: trusty
sudo: false

php:
  - 7.0

stages:
  - build
  - analyze
  - run
  - test

jobs:
  include:
    - stage: build
      name: Build
      script: touch test && ls -la
    - stage: analyze
      name: PHPCS
      script: ./vendor/bin/phpcs -n
    - stage: analyze
      name: Composer validate
      script: composer validate
    - stage: run
      name: Run
      script: ./vendor/bin/drush si minimal
    - stage: test
      name: Behat
      script: ./vendor/bin/behat

before_install:
  - composer --verbose self-update
  - composer --version

install:
  - composer --verbose install
